/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import BO.ClienteBO;
import BO.DoctorBO;
import BO.ServicioBO;
import Entidades.Servicio;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Zuukens
 */
public class HorasMedicas extends javax.swing.JFrame {

    /**
     * Creates new form HorasMedicas
     */
    DoctorBO dbo = new DoctorBO();
    ClienteBO cbo = new ClienteBO();

    public HorasMedicas() {
        initComponents();
        //listarClientes();
        cargarServicio();
        limpiar();
    }

    public void limpiar(){
        txtId.setText("");
        txtId.setVisible(false);
    }
    
    public void listarClientes() {
        dbo.listarHorasMedicas(tbHoras);
    }

    public void cargarServicio() {
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) this.cboServicio.getModel();
        modelo.removeAllElements();
        ArrayList<Servicio> servicio = new ArrayList<Servicio>();
        ServicioBO sb = new ServicioBO();
        servicio = sb.cargarLista();
        modelo.addElement("Seleccione");
        for (Servicio temp : servicio) {
            modelo.addElement(temp);
        }
    }

    public Servicio rescatoNomServicio() {
        Servicio usu = new Servicio();
        usu = (Servicio) this.cboServicio.getSelectedItem();
        return usu;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbHoras = new javax.swing.JTable();
        txtRut = new javax.swing.JTextField();
        cboServicio = new javax.swing.JComboBox<>();
        txtDoctor = new javax.swing.JTextField();
        btnTomar = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();
        btnAtras2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbHoras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbHoras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbHorasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbHoras);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 610, 260));

        txtRut.setBorder(null);
        txtRut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRutKeyReleased(evt);
            }
        });
        jPanel1.add(txtRut, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 160, 20));

        cboServicio.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cboServicio.setMinimumSize(new java.awt.Dimension(32, 25));
        cboServicio.setPreferredSize(new java.awt.Dimension(32, 25));
        cboServicio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboServicioItemStateChanged(evt);
            }
        });
        cboServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboServicioActionPerformed(evt);
            }
        });
        jPanel1.add(cboServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 160, 20));

        txtDoctor.setBorder(null);
        txtDoctor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDoctorKeyReleased(evt);
            }
        });
        jPanel1.add(txtDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 160, 20));

        btnTomar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Tomar.jpg"))); // NOI18N
        btnTomar.setBorder(null);
        btnTomar.setBorderPainted(false);
        btnTomar.setContentAreaFilled(false);
        btnTomar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Tomar 2.jpg"))); // NOI18N
        btnTomar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Tomar 2.jpg"))); // NOI18N
        btnTomar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Tomar 2.jpg"))); // NOI18N
        btnTomar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTomarActionPerformed(evt);
            }
        });
        jPanel1.add(btnTomar, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 390, 110, 30));
        jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 90, 39, -1));

        btnAtras2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Atrás.png"))); // NOI18N
        btnAtras2.setBorderPainted(false);
        btnAtras2.setContentAreaFilled(false);
        btnAtras2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAtras2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Atrás 2.png"))); // NOI18N
        btnAtras2.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Atrás 2.png"))); // NOI18N
        btnAtras2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Atrás 2.png"))); // NOI18N
        btnAtras2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtras2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnAtras2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 40, 40));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Linda Sonrisa.jpg"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 100));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 100, 10));

        jLabel11.setBackground(new java.awt.Color(102, 153, 255));
        jLabel11.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 153, 255));
        jLabel11.setText("Horas Medicas");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 270, 50));

        jLabel24.setBackground(new java.awt.Color(102, 153, 255));
        jLabel24.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(102, 153, 255));
        jLabel24.setText("Buscar Paciente");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 150, -1));

        jSeparator2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 153, 255)));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 220, 190));

        jLabel25.setBackground(new java.awt.Color(102, 153, 255));
        jLabel25.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(102, 153, 255));
        jLabel25.setText("Doctor");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 70, -1));

        jLabel26.setBackground(new java.awt.Color(102, 153, 255));
        jLabel26.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(102, 153, 255));
        jLabel26.setText("Linda Sonrisa");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 100, -1));

        jLabel27.setBackground(new java.awt.Color(102, 153, 255));
        jLabel27.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(102, 153, 255));
        jLabel27.setText("Rut");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 40, -1));

        jLabel28.setBackground(new java.awt.Color(102, 153, 255));
        jLabel28.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(102, 153, 255));
        jLabel28.setText("Servicio");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 70, -1));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 160, 10));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 160, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 904, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cboServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboServicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboServicioActionPerformed

    private void txtRutKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRutKeyReleased
        if (cboServicio.getSelectedIndex() == 0) {
            dbo.filtroHorasRutDoc(tbHoras, txtRut.getText().toUpperCase() + '%', txtDoctor.getText().toUpperCase() + '%');
        } else if (cboServicio.getSelectedIndex() > 0) {
            dbo.filtroHorasServicioRutDoc(tbHoras, txtRut.getText().toUpperCase() + '%', txtDoctor.getText().toUpperCase() + '%', rescatoNomServicio().getNom_servicio());
        }
    }//GEN-LAST:event_txtRutKeyReleased

    private void cboServicioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboServicioItemStateChanged
        if (cboServicio.getSelectedIndex() == 0) {
            dbo.filtroHorasRutDoc(tbHoras, txtRut.getText().toUpperCase() + '%', txtDoctor.getText().toUpperCase() + '%');

        } else if (cboServicio.getSelectedIndex() > 0) {
            dbo.filtroHorasServicioRutDoc(tbHoras, txtRut.getText().toUpperCase() + '%', txtDoctor.getText().toUpperCase() + '%', rescatoNomServicio().getNom_servicio());
        }
    }//GEN-LAST:event_cboServicioItemStateChanged

    private void txtDoctorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDoctorKeyReleased
        if (cboServicio.getSelectedIndex() == 0) {
            dbo.filtroHorasRutDoc(tbHoras, txtRut.getText().toUpperCase() + '%', txtDoctor.getText().toUpperCase() + '%');
        } else if (cboServicio.getSelectedIndex() > 0) {
            dbo.filtroHorasServicioRutDoc(tbHoras, txtRut.getText().toUpperCase() + '%', txtDoctor.getText().toUpperCase() + '%', rescatoNomServicio().getNom_servicio());
        }
    }//GEN-LAST:event_txtDoctorKeyReleased

    private void btnTomarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTomarActionPerformed
        if (txtId.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Seleccione la Hora Medica que desea Tomar");
        } else {
            dbo.eliminarHoraMedica(Integer.parseInt(txtId.getText()));
            String mensaje = dbo.eliminarHoraMedica(Integer.parseInt(txtId.getText()));
            JOptionPane.showMessageDialog(null, mensaje);
            limpiar();
            listarClientes();
            
            if (cboServicio.getSelectedIndex() == 0) {
            dbo.filtroHorasRutDoc(tbHoras, txtRut.getText().toUpperCase() + '%', txtDoctor.getText().toUpperCase() + '%');
        } else if (cboServicio.getSelectedIndex() > 0) {
            dbo.filtroHorasServicioRutDoc(tbHoras, txtRut.getText().toUpperCase() + '%', txtDoctor.getText().toUpperCase() + '%', rescatoNomServicio().getNom_servicio());
        }
        }
    }//GEN-LAST:event_btnTomarActionPerformed

    private void tbHorasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbHorasMouseClicked
        int seleccion = tbHoras.rowAtPoint(evt.getPoint());
        txtId.setText(tbHoras.getValueAt(seleccion, 0) + "");
    }//GEN-LAST:event_tbHorasMouseClicked

    private void btnAtras2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtras2ActionPerformed
        MenuDoctor srb = new MenuDoctor();
        srb.setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAtras2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HorasMedicas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HorasMedicas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HorasMedicas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HorasMedicas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HorasMedicas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras2;
    private javax.swing.JButton btnTomar;
    private javax.swing.JComboBox<String> cboServicio;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable tbHoras;
    private javax.swing.JTextField txtDoctor;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtRut;
    // End of variables declaration//GEN-END:variables
}
