/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import BO.InsumoBO;
import BO.PedidoInsumoBO;
import BO.ProveedorBO;
import Entidades.Insumo;
import Entidades.PedidoInsumo;
import Entidades.Proveedor;
import PDF.Pdf;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.Paragraph;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author marck
 */
public class IngresarInsumosSEC extends javax.swing.JFrame {

    /**
     * Creates new form AgregarInsumo
     */
    
    private Pdf pdf = new Pdf();
    private InsumoBO ibo = new InsumoBO();
    private PedidoInsumoBO pin = new PedidoInsumoBO();
    
    public IngresarInsumosSEC() {
        initComponents();
        listarInsumo();
        limpiar();
        lblCodigo.setVisible(false);
    }

    
    public void listarInsumo() {
        pin.listapedidos(tbInsumos);
    }
    
    public void limpiar() {
        txtInsumo.setText("");
        txtCantidad.setText("");
        txtFecha.setText("");
        txtInsumo.setEnabled(false);
        txtCantidad.setEnabled(false);
        txtID.setVisible(false);
        txtProveedor.setVisible(false);
        txtTipo.setVisible(false);
        txtFamilia.setVisible(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbInsumos = new javax.swing.JTable();
        txtProveedor = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        txtTipo = new javax.swing.JTextField();
        txtFamilia = new javax.swing.JTextField();
        lblCodigo = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtInsumo = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        txtCantidad = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        btnIngresar1 = new javax.swing.JButton();
        btnLimpiar1 = new javax.swing.JButton();
        btnAtras2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbInsumos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbInsumos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbInsumosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbInsumos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 577, 270));
        jPanel1.add(txtProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 380, 51, -1));

        txtID.setText("jTextField1");
        jPanel1.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 380, -1, -1));

        txtTipo.setText("jTextField1");
        jPanel1.add(txtTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 380, -1, -1));

        txtFamilia.setText("jTextField2");
        jPanel1.add(txtFamilia, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 380, -1, -1));
        jPanel1.add(lblCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 331, 107, 17));

        jLabel11.setBackground(new java.awt.Color(102, 153, 255));
        jLabel11.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 153, 255));
        jLabel11.setText("Recepción Insumo");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 350, 50));

        jLabel24.setBackground(new java.awt.Color(102, 153, 255));
        jLabel24.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(102, 153, 255));
        jLabel24.setText("Linda Sonrisa");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 100, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 100, 10));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Linda Sonrisa.jpg"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 100));

        jLabel26.setBackground(new java.awt.Color(102, 153, 255));
        jLabel26.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(102, 153, 255));
        jLabel26.setText("Insumo");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 70, -1));

        txtInsumo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtInsumo.setForeground(new java.awt.Color(255, 255, 255));
        txtInsumo.setBorder(null);
        txtInsumo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInsumoActionPerformed(evt);
            }
        });
        jPanel1.add(txtInsumo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 159, -1));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 160, 10));

        txtCantidad.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtCantidad.setForeground(new java.awt.Color(255, 255, 255));
        txtCantidad.setBorder(null);
        jPanel1.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 159, -1));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 160, 10));

        jLabel23.setBackground(new java.awt.Color(102, 153, 255));
        jLabel23.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(102, 153, 255));
        jLabel23.setText("Cantidad");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 70, -1));

        jLabel25.setBackground(new java.awt.Color(102, 153, 255));
        jLabel25.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(102, 153, 255));
        jLabel25.setText("Fecha Vencimiento");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 140, -1));

        txtFecha.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtFecha.setForeground(new java.awt.Color(255, 255, 255));
        txtFecha.setBorder(null);
        jPanel1.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 159, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 160, 10));

        btnIngresar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Confirmar.jpg"))); // NOI18N
        btnIngresar1.setBorder(null);
        btnIngresar1.setBorderPainted(false);
        btnIngresar1.setContentAreaFilled(false);
        btnIngresar1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Confirmar 2.jpg"))); // NOI18N
        btnIngresar1.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Confirmar 2.jpg"))); // NOI18N
        btnIngresar1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Confirmar 2.jpg"))); // NOI18N
        btnIngresar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresar1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnIngresar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 159, -1));

        btnLimpiar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Limpiar.jpg"))); // NOI18N
        btnLimpiar1.setBorder(null);
        btnLimpiar1.setBorderPainted(false);
        btnLimpiar1.setContentAreaFilled(false);
        btnLimpiar1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Limpiar 2.jpg"))); // NOI18N
        btnLimpiar1.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Limpiar 2.jpg"))); // NOI18N
        btnLimpiar1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Limpiar 2.jpg"))); // NOI18N
        btnLimpiar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiar1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpiar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 130, -1));

        btnAtras2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Atrás.png"))); // NOI18N
        btnAtras2.setBorderPainted(false);
        btnAtras2.setContentAreaFilled(false);
        btnAtras2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAtras2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Atrás 2.png"))); // NOI18N
        btnAtras2.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Atrás 2.png"))); // NOI18N
        btnAtras2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Atrás 2.png"))); // NOI18N
        btnAtras2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtras2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnAtras2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 40, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 942, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tbInsumosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbInsumosMouseClicked
        String var1;
        int seleccion = tbInsumos.rowAtPoint(evt.getPoint());
        txtID.setText(tbInsumos.getValueAt(seleccion, 0) + "");
        txtCantidad.setText(tbInsumos.getValueAt(seleccion, 1) + "");
        txtInsumo.setText(tbInsumos.getValueAt(seleccion, 2) + "");
        txtProveedor.setText(tbInsumos.getValueAt(seleccion, 4) + "");
        txtTipo.setText(tbInsumos.getValueAt(seleccion, 5) + "");
        txtFamilia.setText(tbInsumos.getValueAt(seleccion, 6) + "");
        
        
    }//GEN-LAST:event_tbInsumosMouseClicked

    private void btnIngresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresar1ActionPerformed
        String dia, mes, acno;
        try {
            if (txtFecha.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Ingrese Fecha de Vencimiento en formato ddmmyyy");
            }else{
                Insumo ins = new Insumo();
                PedidoInsumo pinsu = new PedidoInsumo();

                String codigoMaldito = "";

                ins.setStock(Integer.parseInt(txtCantidad.getText()));
                ins.setNom_insumo(txtInsumo.getText());
                String mensaje = ibo.sumarInsumo(ins);
                JOptionPane.showMessageDialog(null, mensaje);

                pinsu.setEstado("COMPLETADO");
                pinsu.setId_pedido(Integer.parseInt(txtID.getText()));
                String mensaje1 = pin.modificarEstado(pinsu);
                JOptionPane.showMessageDialog(null, mensaje1);

                String idp = "";
                String idf = "";
                String fep = "";
                String tip = "";
                String codigo = "";

                idp = txtProveedor.getText();
                fep = txtFecha.getText();
                idf = txtFamilia.getText();
                tip = txtTipo.getText();

                codigo = idp + idf + fep + tip;

                lblCodigo.setText(codigo);

                pdf.Crearpdf(codigo);

                listarInsumo();
            }

            try{
                Runtime.getRuntime().exec("rundll32 url.dll, FileProtocolHandler " + "D:\\Universidad\\Proyectos Java\\ClinicaDental\\PDF\\CodigoDental.pdf");
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Chek File Details");
            }
            limpiar();
        } catch (IOException ex) {
            Logger.getLogger(IngresarInsumos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnIngresar1ActionPerformed

    private void btnLimpiar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiar1ActionPerformed
        limpiar();
    }//GEN-LAST:event_btnLimpiar1ActionPerformed

    private void btnAtras2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtras2ActionPerformed
        MenuSecretaria srb = new MenuSecretaria();
        srb.setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAtras2ActionPerformed

    private void txtInsumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInsumoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInsumoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresarInsumosSEC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresarInsumosSEC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresarInsumosSEC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresarInsumosSEC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IngresarInsumosSEC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras2;
    private javax.swing.JButton btnIngresar1;
    private javax.swing.JButton btnLimpiar1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JTable tbInsumos;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtFamilia;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtInsumo;
    private javax.swing.JTextField txtProveedor;
    private javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables
}
