/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.sql.Connection;
import BD.Conexion;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;


/**
 *
 * @author Zuukens
 */
public class MenuAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form MenuAdministrador
     */
    public MenuAdministrador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnRegistrarProveedor = new javax.swing.JButton();
        btnRegistrarEmpleado = new javax.swing.JButton();
        btnEstadisticas = new javax.swing.JButton();
        btnRegistrarServicios = new javax.swing.JButton();
        btnRegistrarServicios1 = new javax.swing.JButton();
        btnDesconectar = new javax.swing.JButton();
        btnManual = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setToolTipText("");
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(102, 153, 255));
        jLabel7.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 153, 255));
        jLabel7.setText("Menu Administrador");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 370, 50));

        jLabel10.setBackground(new java.awt.Color(102, 153, 255));
        jLabel10.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 153, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Proveedor.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 70, -1));

        jLabel11.setBackground(new java.awt.Color(102, 153, 255));
        jLabel11.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 153, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Empleados.jpg"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 100, 70));

        btnRegistrarProveedor.setBackground(new java.awt.Color(255, 255, 255));
        btnRegistrarProveedor.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Sistema Proveedor.jpg"))); // NOI18N
        btnRegistrarProveedor.setBorderPainted(false);
        btnRegistrarProveedor.setContentAreaFilled(false);
        btnRegistrarProveedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrarProveedor.setDefaultCapable(false);
        btnRegistrarProveedor.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Sistema proveedor 2.jpg"))); // NOI18N
        btnRegistrarProveedor.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Sistema proveedor 2.jpg"))); // NOI18N
        btnRegistrarProveedor.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Sistema proveedor 2.jpg"))); // NOI18N
        btnRegistrarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarProveedorActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrarProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 200, 40));

        btnRegistrarEmpleado.setBackground(new java.awt.Color(255, 255, 255));
        btnRegistrarEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Sistema Empleado.jpg"))); // NOI18N
        btnRegistrarEmpleado.setBorderPainted(false);
        btnRegistrarEmpleado.setContentAreaFilled(false);
        btnRegistrarEmpleado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrarEmpleado.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Sistema Empleado 2.jpg"))); // NOI18N
        btnRegistrarEmpleado.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Sistema Empleado 2.jpg"))); // NOI18N
        btnRegistrarEmpleado.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Sistema Empleado 2.jpg"))); // NOI18N
        btnRegistrarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarEmpleadoActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 200, 41));

        btnEstadisticas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Informes.jpg"))); // NOI18N
        btnEstadisticas.setBorderPainted(false);
        btnEstadisticas.setContentAreaFilled(false);
        btnEstadisticas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEstadisticas.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Informes 2.jpg"))); // NOI18N
        btnEstadisticas.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Informes 2.jpg"))); // NOI18N
        btnEstadisticas.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Informes 2.jpg"))); // NOI18N
        btnEstadisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadisticasActionPerformed(evt);
            }
        });
        jPanel1.add(btnEstadisticas, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 490, 200, 40));

        btnRegistrarServicios.setBackground(new java.awt.Color(255, 255, 255));
        btnRegistrarServicios.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarServicios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Sistema Servicio.jpg"))); // NOI18N
        btnRegistrarServicios.setBorderPainted(false);
        btnRegistrarServicios.setContentAreaFilled(false);
        btnRegistrarServicios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrarServicios.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Sistema Servicio 2.jpg"))); // NOI18N
        btnRegistrarServicios.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Sistema Servicio 2.jpg"))); // NOI18N
        btnRegistrarServicios.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Sistema Servicio 2.jpg"))); // NOI18N
        btnRegistrarServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarServiciosActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrarServicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 200, 40));

        btnRegistrarServicios1.setBackground(new java.awt.Color(255, 255, 255));
        btnRegistrarServicios1.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarServicios1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Sistema Insumo.jpg"))); // NOI18N
        btnRegistrarServicios1.setBorderPainted(false);
        btnRegistrarServicios1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrarServicios1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Sistema Insumo 2.jpg"))); // NOI18N
        btnRegistrarServicios1.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Sistema Insumo 2.jpg"))); // NOI18N
        btnRegistrarServicios1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Sistema Insumo 2.jpg"))); // NOI18N
        btnRegistrarServicios1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarServicios1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrarServicios1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, 200, 40));

        btnDesconectar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Desconectar.jpg"))); // NOI18N
        btnDesconectar.setBorderPainted(false);
        btnDesconectar.setContentAreaFilled(false);
        btnDesconectar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDesconectar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Desconectar 2.jpg"))); // NOI18N
        btnDesconectar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Desconectar 2.jpg"))); // NOI18N
        btnDesconectar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Desconectar 2.jpg"))); // NOI18N
        btnDesconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesconectarActionPerformed(evt);
            }
        });
        jPanel1.add(btnDesconectar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 580, 120, 30));

        btnManual.setBackground(new java.awt.Color(255, 255, 255));
        btnManual.setForeground(new java.awt.Color(255, 255, 255));
        btnManual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Pregunta.png"))); // NOI18N
        btnManual.setBorderPainted(false);
        btnManual.setContentAreaFilled(false);
        btnManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManualActionPerformed(evt);
            }
        });
        jPanel1.add(btnManual, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 40, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Linda Sonrisa.jpg"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 100));

        jLabel13.setBackground(new java.awt.Color(102, 153, 255));
        jLabel13.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 153, 255));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/servicios.png"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 80, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Herramientas dentales.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 80, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/informes.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, 60, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarServiciosActionPerformed
        SistemaServicio srb = new SistemaServicio();
        srb.setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarServiciosActionPerformed

    private void btnRegistrarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarProveedorActionPerformed
        SistemaProveedor srb = new SistemaProveedor();
        srb.setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarProveedorActionPerformed

    private void btnRegistrarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarEmpleadoActionPerformed
        SistemaEmpleado srb = new SistemaEmpleado();
        srb.setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarEmpleadoActionPerformed

    private void btnRegistrarServicios1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarServicios1ActionPerformed
        SistemaInsumoA srb = new SistemaInsumoA();
        srb.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegistrarServicios1ActionPerformed

    private void btnDesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesconectarActionPerformed
        Login srb = new Login();
        srb.setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDesconectarActionPerformed

    private void btnEstadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadisticasActionPerformed
        EstadisticasInformes srb = new EstadisticasInformes();
        srb.setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEstadisticasActionPerformed

    private void btnManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManualActionPerformed
        try {
            Runtime.getRuntime().exec("rundll32 url.dll, FileProtocolHandler " + "D:\\Universidad\\Proyectos Java\\ClinicaDental\\PDF\\Manual de Usuario Escritorio.pdf");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Chek File Details");
        }
    }//GEN-LAST:event_btnManualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDesconectar;
    private javax.swing.JButton btnEstadisticas;
    private javax.swing.JButton btnManual;
    private javax.swing.JButton btnRegistrarEmpleado;
    private javax.swing.JButton btnRegistrarProveedor;
    private javax.swing.JButton btnRegistrarServicios;
    private javax.swing.JButton btnRegistrarServicios1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
