/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import BO.InsumoBO;
import Entidades.TipoFamilia;
import Entidades.TipoInsumo;
import Entidades.Insumo;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Zuukens
 */
public class SistemaInsumoA extends javax.swing.JFrame {

    private InsumoBO ibo = new InsumoBO();

    /**
     * Creates new form SistemaInsumoA
     */
    public SistemaInsumoA() {
        initComponents();
        listarInsumo();
        idMax();
        activo();
        cargarComboInsumo();
        cargarComboFamilia();
    }

    public void listarInsumo() {
        ibo.listarInsumo(tbInsumos);
    }

    public void idMax() {
        txtID.setText(ibo.getMaxID() + "");
    }

    public void activo() {
        txtID.setEnabled(false);
        txtID.setVisible(false);
        txtID2.setEnabled(false);
        txtID2.setVisible(false);
        txtNombre.setEnabled(true);
        cboTipoInsumo.setEnabled(true);
        cboTipoFamilia.setEnabled(true);
        txtPrecio.setEditable(true);
    }

    public void desactivado() {
        txtID.setEnabled(false);
        txtID.setVisible(false);
        txtID2.setEnabled(false);
        txtID2.setVisible(false);
        txtNombre.setEnabled(true);
        cboTipoInsumo.setEnabled(false);
        cboTipoFamilia.setEnabled(false);
        txtPrecio.setEditable(true);
    }

    public void cargarComboInsumo() {
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) this.cboTipoInsumo.getModel();
        modelo.removeAllElements();
        ArrayList<TipoInsumo> insu = new ArrayList<TipoInsumo>();
        InsumoBO in = new InsumoBO();
        insu = in.cargarListaTipo();
        modelo.addElement("Seleccione");
        for (TipoInsumo temp : insu) {
            modelo.addElement(temp);
        }
    }

    public void cargarComboFamilia() {
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) this.cboTipoFamilia.getModel();
        modelo.removeAllElements();
        ArrayList<TipoFamilia> fami = new ArrayList<TipoFamilia>();
        InsumoBO fa = new InsumoBO();
        fami = fa.cargarListaFamilia();
        modelo.addElement("Seleccione");
        for (TipoFamilia temp : fami) {
            modelo.addElement(temp);
        }
    }

    public TipoInsumo rescatoIdTipo() {
        TipoInsumo insu = new TipoInsumo();
        insu = (TipoInsumo) this.cboTipoInsumo.getSelectedItem();
        return insu;
    }

    public TipoFamilia rescatoIdFamilia() {
        TipoFamilia fami = new TipoFamilia();
        fami = (TipoFamilia) this.cboTipoFamilia.getSelectedItem();
        return fami;
    }

    public int rescatoIdTipo2() {
        int idti;
        idti = this.cboTipoInsumo.getSelectedIndex();
        return idti;
    }

    public void limpiar() {
        txtNombre.setText("");
        txtID.setText("");
        txtID2.setText("");
        cboTipoInsumo.setSelectedIndex(0);
        cboTipoFamilia.setSelectedIndex(0);
        txtPrecio.setText("");
    }

    public boolean validarNombre() {
        if (txtNombre.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese Nombre");
            return false;
        } else {
            return true;
        }
    }

    public Boolean validarInsumo() {
        if (cboTipoInsumo.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Seleccione Tipo Insumo");
            return false;
        } else {
            return true;
        }
    }

    public Boolean validarFamilia() {
        if (cboTipoFamilia.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Seleccione Tipo Familia");
            return false;
        } else {
            return true;
        }
    }

    public Boolean validarPrecio() {
        if (txtPrecio.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese Precio");
            return false;
        } else if (!txtPrecio.getText().matches("[0-9]{1,20}")) {
            JOptionPane.showMessageDialog(null, "Ingrese solo Digitos en Precio");
            return false;
        } else {
            return true;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtID = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        cboTipoFamilia = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbInsumos = new javax.swing.JTable();
        btnRegistrar = new javax.swing.JToggleButton();
        btnLimpiar = new javax.swing.JToggleButton();
        btnModificar = new javax.swing.JToggleButton();
        btnEliminar = new javax.swing.JToggleButton();
        txtPrecio = new javax.swing.JTextField();
        txtID2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        btnAtras = new javax.swing.JButton();
        cboTipoInsumo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 70, 34, -1));

        txtNombre.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtNombre.setBorder(null);
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 160, -1));

        cboTipoFamilia.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cboTipoFamilia.setBorder(null);
        cboTipoFamilia.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboTipoFamiliaItemStateChanged(evt);
            }
        });
        jPanel1.add(cboTipoFamilia, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 160, -1));

        tbInsumos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbInsumos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbInsumosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbInsumos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 680, 280));

        btnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Registrar.jpg"))); // NOI18N
        btnRegistrar.setBorder(null);
        btnRegistrar.setBorderPainted(false);
        btnRegistrar.setContentAreaFilled(false);
        btnRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Registrar 2.jpg"))); // NOI18N
        btnRegistrar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Registrar 2.jpg"))); // NOI18N
        btnRegistrar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Registrar 2.jpg"))); // NOI18N
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 130, 30));

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Limpiar.jpg"))); // NOI18N
        btnLimpiar.setBorder(null);
        btnLimpiar.setBorderPainted(false);
        btnLimpiar.setContentAreaFilled(false);
        btnLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpiar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Limpiar 2.jpg"))); // NOI18N
        btnLimpiar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Limpiar 2.jpg"))); // NOI18N
        btnLimpiar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Limpiar 2.jpg"))); // NOI18N
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 130, 31));

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Modificar.jpg"))); // NOI18N
        btnModificar.setBorder(null);
        btnModificar.setBorderPainted(false);
        btnModificar.setContentAreaFilled(false);
        btnModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModificar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Modificar 2.jpg"))); // NOI18N
        btnModificar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Modificar 2.jpg"))); // NOI18N
        btnModificar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Modificar 2.jpg"))); // NOI18N
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 130, 31));

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Eliminar.jpg"))); // NOI18N
        btnEliminar.setBorder(null);
        btnEliminar.setBorderPainted(false);
        btnEliminar.setContentAreaFilled(false);
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Eliminar 2.jpg"))); // NOI18N
        btnEliminar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Eliminar 2.jpg"))); // NOI18N
        btnEliminar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Eliminar 2.jpg"))); // NOI18N
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 130, 31));

        txtPrecio.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtPrecio.setBorder(null);
        jPanel1.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 160, -1));
        jPanel1.add(txtID2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 70, 34, -1));

        jLabel11.setBackground(new java.awt.Color(102, 153, 255));
        jLabel11.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 153, 255));
        jLabel11.setText("Sistema Insumo");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 290, 50));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Linda Sonrisa.jpg"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 100));

        jLabel22.setBackground(new java.awt.Color(102, 153, 255));
        jLabel22.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(102, 153, 255));
        jLabel22.setText("Precio Compra");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 110, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 100, 10));

        jLabel23.setBackground(new java.awt.Color(102, 153, 255));
        jLabel23.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(102, 153, 255));
        jLabel23.setText("Linda Sonrisa");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 100, -1));

        jLabel24.setBackground(new java.awt.Color(102, 153, 255));
        jLabel24.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(102, 153, 255));
        jLabel24.setText("Nombre");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 70, -1));

        jLabel25.setBackground(new java.awt.Color(102, 153, 255));
        jLabel25.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(102, 153, 255));
        jLabel25.setText("Tipo Insumo");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 100, -1));

        jLabel26.setBackground(new java.awt.Color(102, 153, 255));
        jLabel26.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(102, 153, 255));
        jLabel26.setText("Familia Insumo");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 110, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 160, 10));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 160, 10));

        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Atrás.png"))); // NOI18N
        btnAtras.setBorderPainted(false);
        btnAtras.setContentAreaFilled(false);
        btnAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAtras.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Atrás 2.png"))); // NOI18N
        btnAtras.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Atrás 2.png"))); // NOI18N
        btnAtras.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Atrás 2.png"))); // NOI18N
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        jPanel1.add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 40, 40));

        cboTipoInsumo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cboTipoInsumo.setBorder(null);
        cboTipoInsumo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboTipoInsumoItemStateChanged(evt);
            }
        });
        cboTipoInsumo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTipoInsumoActionPerformed(evt);
            }
        });
        cboTipoInsumo.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cboTipoInsumoPropertyChange(evt);
            }
        });
        jPanel1.add(cboTipoInsumo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 160, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1030, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        if (validarNombre() == false || validarInsumo() == false || validarFamilia() == false || validarPrecio() == false) {
        } else {

            Insumo ins = new Insumo();

            ins.setId_insumo(Integer.parseInt(txtID.getText()));
            ins.setNom_insumo(txtNombre.getText().toUpperCase());
            ins.setStock(0);
            ins.setId_tipo_insumo(rescatoIdTipo().getId_tipo_insumo());
            ins.setId_tipo_familia(rescatoIdFamilia().getId_tipo_familia());
            ins.setPrecio_compra(Integer.parseInt(txtPrecio.getText()));

            String mensaje = ibo.agregarInsumo(ins);
            JOptionPane.showMessageDialog(null, mensaje);

            listarInsumo();
            limpiar();
            idMax();
        }       
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        activo();
        limpiar();
        idMax();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        if (txtID2.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Seleccione el Insumo que desea Modificar");
        } else if (validarPrecio() == false) {
        } else {

            Insumo ins = new Insumo();

            ins.setId_insumo(Integer.parseInt(txtID.getText()));
            ins.setNom_insumo(txtNombre.getText().toUpperCase());
            ins.setPrecio_compra(Integer.parseInt(txtPrecio.getText()));

            String mensaje = ibo.modificarPrecio(ins);
            JOptionPane.showMessageDialog(null, mensaje);

            listarInsumo();
            activo();
            limpiar();
            idMax();
        }

    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (txtID2.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Seleccione el Insumo que desea Eliminar");
        } else {
            String mensaje = ibo.eliminarInsumo(Integer.parseInt(txtID.getText()));
            JOptionPane.showMessageDialog(null, mensaje);
            limpiar();
            listarInsumo();
            idMax();
            activo();
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void cboTipoFamiliaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboTipoFamiliaItemStateChanged
        if (this.cboTipoInsumo.getSelectedIndex() > 0) {
            TipoFamilia tipo = new TipoFamilia();
            tipo = (TipoFamilia) this.cboTipoFamilia.getSelectedItem();
        }
    }//GEN-LAST:event_cboTipoFamiliaItemStateChanged

    private void tbInsumosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbInsumosMouseClicked
        String var1;
        int seleccion = tbInsumos.rowAtPoint(evt.getPoint());
        txtID.setText(tbInsumos.getValueAt(seleccion, 0) + "");
        txtID2.setText(tbInsumos.getValueAt(seleccion, 0) + "");
        txtNombre.setText(tbInsumos.getValueAt(seleccion, 1) + "");
        txtPrecio.setText(tbInsumos.getValueAt(seleccion, 5) + "");
        cboTipoInsumo.setEnabled(false);
        cboTipoFamilia.setEnabled(false);
        txtNombre.setEnabled(false);


    }//GEN-LAST:event_tbInsumosMouseClicked

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        MenuAdministrador srb = new MenuAdministrador();
        srb.setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void cboTipoInsumoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboTipoInsumoItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cboTipoInsumoItemStateChanged

    private void cboTipoInsumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTipoInsumoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboTipoInsumoActionPerformed

    private void cboTipoInsumoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cboTipoInsumoPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_cboTipoInsumoPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SistemaInsumoA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SistemaInsumoA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SistemaInsumoA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SistemaInsumoA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SistemaInsumoA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JToggleButton btnEliminar;
    private javax.swing.JToggleButton btnLimpiar;
    private javax.swing.JToggleButton btnModificar;
    private javax.swing.JToggleButton btnRegistrar;
    private javax.swing.JComboBox<String> cboTipoFamilia;
    private javax.swing.JComboBox<String> cboTipoInsumo;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable tbInsumos;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtID2;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables

}
